"""Append only record store with commit watermark and tombstones."""

from .errors import StoreError, TombstoneConflict, UnknownRecord, WatermarkRegression
from .kinds import (
    CONTROL_KINDS,
    KIND_ALARM_CLEAR,
    KIND_ALARM_SET,
    KIND_AUDIT,
    KIND_BREAKER_CLOSE,
    KIND_BREAKER_LATCH_RELEASE,
    KIND_BREAKER_OPEN,
    KIND_BREAKER_TRIP,
    KIND_COMMIT,
    KIND_CONFIG_PARAM,
    KIND_ENGINE_START,
    KIND_ENGINE_CRANK,
    KIND_ENGINE_STOP,
    KIND_FUEL_DELIVER,
    KIND_GOV_ADJUST,
    KIND_LOAD_ADJUST,
    KIND_LUBE_LATCH_CLEAR,
    KIND_LUBE_LATCH_SET,
    KIND_LUBE_PRESSURE,
    KIND_ROLLBACK,
    KIND_SYNC_BASELINE,
    KIND_SYNC_COMMIT,
    KIND_SYNC_PERSIST,
    KIND_TOMBSTONE,
    is_control,
)
from .log import AppendOnlyLog
from .records import Record
from .snapshot import SnapshotPayload, read_snapshot, validate_against_log, write_snapshot

__all__ = [
    "AppendOnlyLog",
    "CONTROL_KINDS",
    "KIND_ALARM_CLEAR",
    "KIND_ALARM_SET",
    "KIND_AUDIT",
    "KIND_BREAKER_CLOSE",
    "KIND_BREAKER_LATCH_RELEASE",
    "KIND_BREAKER_OPEN",
    "KIND_BREAKER_TRIP",
    "KIND_COMMIT",
    "KIND_CONFIG_PARAM",
    "KIND_ENGINE_START",
    "KIND_ENGINE_CRANK",
    "KIND_ENGINE_STOP",
    "KIND_FUEL_DELIVER",
    "KIND_GOV_ADJUST",
    "KIND_LOAD_ADJUST",
    "KIND_LUBE_LATCH_CLEAR",
    "KIND_LUBE_LATCH_SET",
    "KIND_LUBE_PRESSURE",
    "KIND_ROLLBACK",
    "KIND_SYNC_BASELINE",
    "KIND_SYNC_COMMIT",
    "KIND_SYNC_PERSIST",
    "KIND_TOMBSTONE",
    "Record",
    "SnapshotPayload",
    "StoreError",
    "TombstoneConflict",
    "UnknownRecord",
    "WatermarkRegression",
    "is_control",
    "read_snapshot",
    "validate_against_log",
    "write_snapshot",
]
